### ISSUE TITLE
3DS Clarification

### ISSUE THREAD

**Issue by Flinted** [Judopay/JudoKit-Android#131]
EDIT: Re-writing this for clarity as we were conflating 3DS and 3DS2 from the testing docs. Unfortunately the same issue remains. 
https://docs.judopay.com/en/testing-and-go-live/sandbox-testing.html#test-case-6

Hey there, hoping you can help. 

We are attempting to integrate JudoPay to our app and we are having some issues with the 3DS side of things.

We are using PaymentSession Id from our back end for authorization and in the Sandbox we are able to process successful test payments and pick up the Webhooks confirming the payment for the backend 👍 

The issue we are having is when we attempt to trigger a 3DS check on the Sandbox environment.  

**Expected Result:**
JudoPay should start a mock 3DS verification view to handle the requires 3DS.

**Actual Result:**
We appear to get a `PAYMENT_SUCCESS` flagged result back with a message = "Card Referred"  and result = "Declined"

**SDK Version** 
- 2.1.3

**Steps to recreate:**

- Start judo pay SDK in Sandbox mode
- Use Payment Session auth
- Start `JudoActivity`
- Input following details in Card Entry bottomsheet:

Card: 4104 7100 0000 5315
Name: Julie Bean
Expiry: 12/25
CV2:  487

- Hit Pay.

Are we missing something on how to trigger the 3DS flow from the client side should we see the "Card Referred" message?

Cheers!
Flint

**Comment by Flinted** [comment]
Further to the above:

I see now that there is a handling of this internal to the SDK in the CardEntryFragment.

Seeing the receipt come back the message is Card Referred but the `receipt.is3dSecureRequired` check seems to return false as all of 1acsUrl` `md` and `paReq` are null. 

As such the Declined status and error message are passed out to the consumer as a PAYMENT_SUCCESS

**Comment by freddy-onco** [comment]
Hi @Flinted , thank you for your query, I will reach out to you by email.
