### ISSUE TITLE
Unable to initialing Judo payment for 3DSeure on Samsung Device SM-S908B

### ISSUE THREAD

**Issue by asadzahoor008** [Judopay/JudoKit-Android#197]
when I try to initialize the 3DSeure SDK on this device model SM-S908B it throws an exception and the message display "getGroupIdLevel", I review the exception it happened while gathering device information after this exception the process is stopped then we are unable to do any transaction. below I shared the code where I'm calling

threeDS2Service.initialize(
                    activityContext,
                    parameters,
                    Locale.getDefault(),
                    null
                )
I'm using this version -->>  'com.judopay:judokit-android:4.0.0'

please help me to fix this issue. Thanks

**Comment by stefan-tudor** [comment]
Hey @asadzahoor008,

Thank you for reporting this,
This issue is fixed in [version 4.0.1](https://github.com/Judopay/JudoKit-Android/releases/tag/v4.0.1); please update to the latest version

**Comment by asadzahoor008** [comment]
thank you so much for your response @stefan-tudor
