### ISSUE TITLE
4.0.1 is incompatibility issue with kotlin version

### ISSUE THREAD

**Issue by asadzahoor008** [Judopay/JudoKit-Android#198]
I have updated the dependency to 4.0.1 but it giving an error can you please help me on this issue?
C:/Users/abcd/.gradle/caches/transforms-3/e81010dcd6bbbb320efb1d3beab1a994/transformed/jetified-judo3ds2-1.3.0-api.jar!/META-INF/Judo3DS2_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.

**Comment by stefan-tudor** [comment]
Hey,

Looks like your project is using Kotlin 1.6.0, try updating your `ext.kotlin_version` in your project `build.gradle` from `1.6.0` to the latest version available.
