### ISSUE TITLE
Autofill support for card field

### ISSUE THREAD

**Issue by andreichykov** [Judopay/JudoKit-Android#222]
Currently sdk does not allow to use built-in android features for card entering or scanning. Is only possible if user long taps on field and enables autofill which is not obvious for all the users. Can you please add the feature as default behavior?

https://developer.android.com/guide/topics/text/autofill-optimize#credit-card-info

![photo_2023-11-07 18 24 18](https://github.com/Judopay/JudoKit-Android/assets/5869152/39f69a4d-7f1b-4bcf-b238-6aeb06ed03b4)
![photo_2023-11-07 18 24 20](https://github.com/Judopay/JudoKit-Android/assets/5869152/7e926337-5b32-4ba2-95dc-c825bd0959e9)

**Comment by stefan-tudor** [comment]
Hey @andreichykov,
Thank you for raising this,

We're on it!
